# Generated by Django 4.0.1 on 2022-03-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summernote_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='summernote_AbstractAttachment',
            new_name='Attachment',
        ),
        migrations.DeleteModel(
            name='summernote_Attachment',
        ),
    ]
