# Generated by Django 4.0.1 on 2022-03-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summernote_support', '0003_rename_attachment_mink_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mink_Attachment',
        ),
    ]
