# Generated by Django 4.0.1 on 2022-02-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_article_voter_comment_voter_alter_article_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_photo',
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, verbose_name='상품명(내부용)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.TextField(verbose_name='이미지'),
        ),
    ]
